### ISSUE TITLE
My program crashed the VM

### ISSUE THREAD

**Issue by eekee** [SBTCVM/SBTCVM-Mark-2#8]
I broke it with my first program!

Hahahaha oh dear! Github "doesn't support" attaching .tasm or .trom... or seemingly any source code. What is this I don't even! Aaaanyway, pasting the tasm since it's so short:

```
setreg1|--------+|overloop
# label could go on next statement, but if it loops wrong i want to see it.

setreg2|+--------
dumpreg1|0|leftloop
multiply|3
wait|-
gotodataif|>nextloop
gotodata|>leftloop

setreg2|--------+|nextloop
dumpreg1|0|rightloop
divide|3
wait|-
gotodataif|>overloop
gotodata|>rightloop
```

It assembled with no errors, reporting 4 gotorefs, 13 instructions, and extra space: 19670.

On running it, the VM window opens, then soon closes. Here is the console output:
![image](https://user-images.githubusercontent.com/7953411/35286263-67787f8c-0057-11e8-9de3-36f8cb8eeb7c.png)

Since I laughed at Github earlier, I'll say I'm happy to see I can attach a screenshot with print screen and ctrl-V.

They say you don't really find the bugs in your code until someone else uses it. :)

**Comment by ThomasTheSpaceFox** [comment]
ah. yea the assembler doesn't exactly tell you when the syntax is wrong. (known bug) you may want to take a look at the assembly section of the users manual.  the basic arithmetic operations are add, sub, mul, and div. and they work on the values in Registers 1 and 2. and populate register 1 with the result. second, the wait instruction supports a decimal syntax. like so:
`wait|:6.2`
The actual operation takes a ternary-encoded fixed point number with a range from 0 to 19.683

The assembler is a bit, well dumb. most instructions will treat whats between the first and second separators as 9-trit wide ternary data... what happens is the trom winds up having lines that are too short and contain invalid characters that the VM simply doesn't know what to do with.

**Comment by ThomasTheSpaceFox** [comment]
if what is in the users manual doesn't work or doesn't help, check some of the dozen-or-so test roms and accompanying source code.  a good algorithm example would be fib.tasm (in VMSYSTEM/ROMS)

**Comment by eekee** [comment]
Ah I see! Thank you.

Not promising anything, but I'll see what I can do to improve SBTCVM-asm.txt.

**Comment by eekee** [comment]
All sorted, thanks!
